language:
  - python

python:
  - "3.6"

install:
  - pip install pandas
  - pip install numpy
  - pip install flake8
  - pip install ipython
  - pip install matplotlib
  - pip install ipywidgets
script:
  - python script.py

after_success:
  - flake8 --max-line-length 100 --ignore=E121,E123,E126,E221,E222,E225,E226,E242,E701,E702,E704,E731,W503 .

notifications:
  email: false
